#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=AMCR | grep "\.php$")

if echo "$files" | grep --quiet "\.php$"; then
    echo "Run Duster to lint the code"
    ./vendor/bin/duster lint $files

    if [ $? -ne 0 ]; then
        echo "Code check failed! Please fix the issues above and try committing again."
        exit 1
    fi

    echo "Run Rector to detect issues"
    ./vendor/bin/rector process --dry-run $files

    if [ $? -ne 0 ]; then
        echo "Rector detecting issues. Please fix the issues above and try committing again."
        exit 1
    fi
fi

js_files=$(git diff --cached --name-only --diff-filter=AMCR)

if echo "$js_files"; then
    echo "Run ESLint..."
    npx eslint $js_files --fix

    if [ $? -ne 0 ]; then
        echo "ESLint detected issues. Please fix the issues above and try committing again."
        exit 1
    fi
fi

exit 0