#!/bin/sh

# Get PHP files
php_files=$(git diff --cached --name-only --diff-filter=AMCR | grep "\.php$")

# Run PHP linters if there are PHP files
if [ -n "$php_files" ]; then
    echo "Run Duster to lint the code"
    ./vendor/bin/duster lint $php_files || {
        echo "Code check failed! Please fix the issues above and try committing again."
        exit 1
    }

    echo "Run Rector to detect issues"
    ./vendor/bin/rector process --dry-run $php_files || {
        echo "Rector detecting issues. Please fix the issues above and try committing again."
        exit 1
    }
fi

# Get all staged files for ESLint
js_files=$(git diff --cached --name-only --diff-filter=AMCR)

# Run ESLint if there are files to check
if [ -n "$js_files" ]; then
    echo "Run ESLint..."
    npx eslint $js_files || {
        echo "ESLint detected issues. Please fix the issues above and try committing again."
        exit 1
    }
    echo "ESLint passed."
    echo ""
fi

exit 0