name: velora
recipe: laravel
config:
  webroot: public
  via: nginx
  php: "8.5"
  cache: redis
services:
  node:
    type: node:24
    ssl: true
    sslExpose: true
    build:
      - npm install -g pnpm@latest-10
      - pnpm install
    command: pnpm dev
    ports:
      - 5173:5173
  database:
    type: mysql
    creds:
      user: velora
      password: velora
      database: velora
    portforward: 3307
tooling:
  dev:
    service: node
    cmd: pnpm dev
excludes:
  - node_modules
  - vendor
  - .pnpm-store