/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "welcome": [],
    "home": [],
    "login": [],
    "auth.login": [],
    "auth.logout": [],
    "signup": [],
    "auth.signup": [],
    "password.forgot": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "auth.social.redirect": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "auth.social.callback": [
        {
            "name": "provider",
            "required": true
        }
    ],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "trips.index": [],
    "trips.create": [],
    "trips.store": [],
    "trips.show": [
        {
            "name": "trip",
            "required": true,
            "binding": "id"
        }
    ],
    "trips.itineraries.create": [
        {
            "name": "trip",
            "required": true,
            "binding": "id"
        }
    ],
    "trips.itineraries.store": [
        {
            "name": "trip",
            "required": true,
            "binding": "id"
        }
    ],
    "trips.users.store": [
        {
            "name": "trip",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
